from .prompt_selector import NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS
from .prompt_selector import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS
from .easy_lora_loader import NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS
from .easy_lora_loader import NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS
import os

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **PROMPT_NODE_CLASS_MAPPINGS,
    **LORA_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

WEB_DIRECTORY = "./web"
